"""Cookie测试Fixture模块

提供Cookie相关的测试fixture，包括示例Cookie数据和Cookie处理器mock。
"""

import pytest
from unittest.mock import MagicMock
from pathlib import Path


@pytest.fixture
def sample_cookie_data():
    """示例Cookie数据"""
    return {"session_id": "abc123def456", "user_token": "token789xyz", "csrf_token": "csrf123abc"}


@pytest.fixture
def sample_cookie_list():
    """示例Cookie列表（浏览器格式）"""
    return [
        {
            "name": "session_id",
            "value": "abc123def456",
            "domain": ".dingtalk.com",
            "path": "/",
            "secure": True,
            "httpOnly": True,
        },
        {
            "name": "user_token",
            "value": "token789xyz",
            "domain": ".dingtalk.com",
            "path": "/",
            "secure": True,
            "httpOnly": True,
        },
        {
            "name": "csrf_token",
            "value": "csrf123abc",
            "domain": ".dingtalk.com",
            "path": "/",
            "secure": False,
            "httpOnly": False,
        },
    ]


@pytest.fixture
def sample_cookie_string():
    """示例Cookie字符串格式"""
    return "session_id=abc123def456; user_token=token789xyz; csrf_token=csrf123abc"


@pytest.fixture
def sample_cookie_file(tmp_path):
    """示例Cookie文件"""
    cookie_file = tmp_path / "cookies.txt"
    cookie_content = """# Netscape HTTP Cookie File
# This file is generated by the browser

.dingtalk.com	TRUE	/	FALSE	1735689600	session_id	abc123def456
.dingtalk.com	TRUE	/	FALSE	1735689600	user_token	token789xyz
.dingtalk.com	TRUE	/	FALSE	1735689600	csrf_token	csrf123abc
"""
    cookie_file.write_text(cookie_content, encoding="utf-8")
    return cookie_file


@pytest.fixture
def sample_cookie_json_file(tmp_path):
    """示例Cookie JSON文件"""
    cookie_file = tmp_path / "cookies.json"
    cookie_content = """{
    "cookies": [
        {
            "name": "session_id",
            "value": "abc123def456",
            "domain": ".dingtalk.com",
            "path": "/",
            "secure": true,
            "httpOnly": true
        },
        {
            "name": "user_token",
            "value": "token789xyz",
            "domain": ".dingtalk.com",
            "path": "/",
            "secure": true,
            "httpOnly": true
        }
    ]
}"""
    cookie_file.write_text(cookie_content, encoding="utf-8")
    return cookie_file


@pytest.fixture
def mock_cookie_handler():
    """Mock Cookie处理器"""
    mock_handler = MagicMock()
    mock_handler.get_cookie.return_value = "session_id=abc123def456; user_token=token789xyz"
    mock_handler.get_headers.return_value = {
        "Cookie": "session_id=abc123def456; user_token=token789xyz"
    }
    mock_handler.get_live_name.return_value = "测试直播"
    return mock_handler


@pytest.fixture
def cookie_with_live_name():
    """包含直播名称的Cookie数据"""
    return {"session_id": "abc123def456", "user_token": "token789xyz", "live_name": "测试直播回放"}


@pytest.fixture
def cookie_with_special_chars():
    """包含特殊字符的Cookie数据"""
    return {"session_id": "abc!@#123", "user_token": "token$%^789", "csrf_token": "csrf&*()abc"}


@pytest.fixture
def cookie_with_unicode():
    """包含Unicode字符的Cookie数据"""
    return {
        "session_id": "abc123",
        "user_token": "token789",
        "live_name": "测试直播🎥",
        "description": "这是一个测试直播回放",
    }


@pytest.fixture
def empty_cookie_data():
    """空Cookie数据"""
    return {}


@pytest.fixture
def invalid_cookie_data():
    """无效的Cookie数据"""
    return {"session_id": None, "user_token": "", "csrf_token": 12345}


@pytest.fixture
def cookie_with_expiry():
    """包含过期时间的Cookie数据"""
    return [
        {
            "name": "session_id",
            "value": "abc123",
            "expiry": 1735689600,
            "domain": ".dingtalk.com",
            "path": "/",
        },
        {
            "name": "user_token",
            "value": "token789",
            "expiry": 1735689600,
            "domain": ".dingtalk.com",
            "path": "/",
        },
    ]
